### PR TITLE
[Chore] App logo and application name

### LINKED ISSUE #15: [Chore] Setup project
## Why

Setup repo
 
## Acceptance Criteria

Create git repo for Android "SMS Forwarder"

### PR DESCRIPTION
**Pull request by lydiasama**
## What happened 🤔
Initial app logo

## Insight 👀
- Add app logo
- Rename application

### CODE REVIEW

**Review by hoangnguyen92dn — APPROVED** [review]
The best app launcher icon I've ever seen 🚀

**Comment by hoangnguyen92dn** [comment]
@lydiasama What do you think about updating `primaryColor` and `accentColor` in this PR? 🤔

**Comment by lydiasama** [comment]
@hoangnguyen92dn I updated in #5  instead with another style. 🥺

**Comment by hoangnguyen92dn** [comment]
👌So let merge this PR 😁

**Review by luongvo — APPROVED** [review]
lgtm

**Pull request merged**
